name: run python job
on: [push]
jobs:
  run-python-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check python version
        run: python --version
      - name: run python file
        run: python3 hello.py 